### ISSUE TITLE
QCC file format

### ISSUE THREAD

**Issue by JohanGahnstrom** [interlark/qdc-converter#1]
I understand that one of the few ways to export Garmin Garmin Quickdraw Maps (i.e. contours) is to use the community.
Its noted here.
https://www.garmin.com/en-US/blog/fish-and-hunt/download-bathymetric-charts-garmin-quickdraw/
The exported file is in QCC file format.
Is this the same format as the QDC format? Or where can I get the QDC files from my device?

If they are different, it would be great to add the QCC feature to this as it could the use other users data as well to produce charts.

Cheers and thanks for your great effort

**Comment by interlark** [comment]
Hi. Those are different formats. Converting `.qcc` to `.qdc` could be a bit tricky process, but doable if you have Android phone or Android emulator on your computer.

I added a small guide to the README if someone bump into the same question in future.

## Convert `.qcc` to `.qdc` files with Android phone
If you have only `.qcc` file, you should convert it to `.qdc` files to use in `qdc-converter`.

1. Install `Garmin ActiveCaptain` Android app.
    > https://play.google.com/store/apps/details?id=com.garmin.android.marine<br/>
    > https://apk.support/download-app/com.garmin.android.marine

2. Launch app, sign up and close it.

2. Copy `.qcc` file to the phone path `/Android/data/com.garmin.android.marine/files/Garmin/esm/internal0/`

3. Launch `Garmin ActiveCaptain` app and wait until it converts the source `.qcc` file to `.qdc` files.
    > The process usually takes less than a minute.

4. Copy folder with `.qdc` files from phone path `/Android/data/com.garmin.android.marine/files/Garmin/esm/internal0/Garmin/Quickdraw/Contours/C/` to your computer.

**Comment by JohanGahnstrom** [comment]
Perfect!
Thanks for the help



Johan Gahnström
CompetenSEA Limited
+44 1273 90 1799
